{% set version = "0.25.0" %}

package:
  name: evalml-core
  version: '{{ version }}'

source:
  url: https://test-files.pythonhosted.org/packages/8d/32/d9f33c96bab045b97afe7fd89d60326e7cda490d27b3d76db54b612b60d2/evalml-freddyaboulton-test-0.24.2.tar.gz
  sha256: 7dd3333d053dda3fb54c4103cefdf10e92782011174bf7366f5aa0b2cde51104

build:
  number: 0

outputs:
  - name: evalml-core
    build:
      entry_points:
        - evalml = evalml.__main__:cli
      noarch: python
    script: build_script.sh
    requirements:
      host:
        - python >=3.7
        - pip
      run:
        - numpy >=1.19.1
        - pandas >=1.1.0
        - scipy >=1.2.1
        - scikit-learn >=0.23.1
        - scikit-optimize >=0.8
        - colorama
        - cloudpickle >=0.2.2
        - click >=7.0.0
        - psutil >=5.6.3
        - requirements-parser >=0.2.0
        - shap >=0.35.0
        - texttable >=1.6.2
        - woodwork ==0.3.1
        - featuretools>=0.20.0
        - nlp-primitives>=1.1.0
        - python >=3.7.*
        - networkx >=2.5
        - pytest-xdist
    test:
      imports:
        - evalml
      requires:
        - pytest >= 4.4.*
        - nbval ==0.9.3
        - python-graphviz >=0.8.4
        - category_encoders >=2.0.0
      source_files:
        - evalml/*
        - requirements.txt
        - core-requirements.txt
      commands:
        - pytest evalml/tests -n 8 --has-minimal-dependencies

  - name: evalml
    build:
      noarch: python
    requirements:
      run:
        - '{{ pin_subpackage("evalml-core", max_pin="x.x.x.x") }}'
        - plotly >=4.14.1
        - python-kaleido ==0.1.0
        - matplotlib-base >=3.3.3
        - seaborn >=0.11.0
        - ipywidgets >=7.5
        - py-xgboost >=0.82,<1.3.0
        - catboost >=0.20
        - lightgbm >=2.3.1
        - python >=3.7.*
        - statsmodels >=0.12.2
        - imbalanced-learn >=0.7.0
        - sktime >=0.5.3
    test:
      imports:
        - evalml
      requires:
        - pytest ==4.4.1
        - nbval ==0.9.3
        - python-graphviz >=0.8.4
        - category_encoders >=2.0.0
      source_files:
        - evalml/*
        - requirements.txt
        - core-requirements.txt
      commands:
        - pytest evalml/tests -n 8 --is-using-conda

about:
  doc_url: https://evalml.featurelabs.com/
  dev_url: https://github.com/alteryx/evalml/
  home: https://www.alteryx.com/innovation-labs
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: EvalML is an AutoML library that builds, optimizes, and evaluates machine learning pipelines using domain-specific objective functions.

extra:
  recipe-maintainers:
    - dsherry
    - freddyaboulton
    - ParthivNaresh
    - angela97lin
    - bchen1116
    - chukarsten
